

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: sante_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: sante_backend
    restart: unless-stopped
    env_file:
      - backend/.env  # variables d'environnement back
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=sante_db
      - REDIS_URL=redis://redis:6379
      - DEMO_MODE=true  # autorise l'admin à consulter les données santé en mode démo
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  ia_service:
    build:
      context: ./services/ia_service
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=sante_db
      - REDIS_URL=redis://redis:6379
      - DEMO_MODE=true  # autorise l'admin à consulter les données santé en mode démo
    ports:
      - "8001:8001"
    command: ["uvicorn", "main:aapp", "--host", "0.0.0.0", "--port", "8001"]

  notification_service:
    build:
      context: ./services/notification_service
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DEMO_MODE=true  # autorise l'admin à consulter les données santé en mode démo
    ports:
      - "8002:8002"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:80"

  # frontend (optionnel, à ajouter plus tard)
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: sante_frontend
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5173:5173"

  ia_test:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
      - redis
      - ia_service
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=sante_db
      - REDIS_URL=redis://redis:6379
    command: bash -c "pip install -r requirements.txt && python test_ia_reco.py"
    networks:
      - default

volumes:
  mongo_data:
    driver: local
