name: CI Backend

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

        
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest httpx

      - name: Exécution des tests Pytest
        run: |
          pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image Docker backend
        run: |
          docker build -t sante-backend:ci ./backend
